name: Build
on: 
  push:
  pull_request:
    tags:
      - "v*"
jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.idtag }}
        run: |
          gh release create [<v0.0.1>] [<*>]  \
            --repo= "$market-place" \
            --title= "${v}" \
            --latest \
            --generate-notes
            
